// Cells read out of the team's FORMID LOCATIONS sheet. Travel with
// `coc <EditorID>`; the form id is there for /teleport and the like.
const CELLS = [
  ['AAADeleteWhenDoneTestJeremy', '0x0006C3B6'],
  ['aaaMarkers', '0x0005EAC7'],
  ['AbandonedPrison01', '0x00021594'],
  ['AbandonedShackInterior', '0x00050F1E'],
  ['Alftand01', '0x000152C3'],
  ['Alftand02', '0x00056C1B'],
  ['AlftandBlackreach01', '0x000237BD'],
  ['AlftandWorldEnd', '0x0006987A'],
  ['AlftandWorldForge', '0x00069879'],
  ['AlftandWorldOrigin', '0x0006987F'],
  ['AlftandWorldStart', '0x00069881'],
  ['AlftandZCell', '0x00069858'],
  ['Angarvunde01', '0x000152C1'],
  ['Angarvunde02', '0x0002D525'],
  ['Angarvunde03', '0x0002D524'],
  ['AngasMillAerisHouse', '0x0001620B'],
  ['AngasMillCommonHouse', '0x00016209'],
  ['AngasMillEdge', '0x00009092'],
  ['AnisesCabin01', '0x000DDF7C'],
  ['Ansilvund01', '0x000152C0'],
  ['Ansilvund02', '0x0001F358'],
  ['Avanchnzel01', '0x000152BE'],
  ['Avanchnzel02', '0x00037B76'],
  ['Avanchnzel03', '0x0004C6DD'],
  ['AzurasStarInterior01', '0x000152BD', 'Blackscreen?'],
  ['AzuraVoiceCell', '0x00028ACF'],
  ['BattleBornFarm', '0x00016207'],
  ['BearsCaveMillEdge', '0x00009C5A'],
  ['BilegulchMine', '0x0001B147'],
  ['BlackBriarLodge01', '0x000A6D8E'],
  ['BlackreachArena', '0x000237D5'],
  ['BlackreachCity', '0x000237DE'],
  ['BlackreachElevatorAlftand', '0x000237B4'],
  ['BlackreachElevatorMzinchaleft', '0x0002375F'],
  ['BlackreachElevatorRaldbthar', '0x0001EE6E'],
  ['BlackreachFungusField', '0x000237D3'],
  ['BlackreachOrigin', '0x0001EE7A'],
  ['BlackreachOverpass', '0x000237DF'],
  ['BlackreachPumpStation', '0x000237D7'],
  ['BlackreachQuickExitAlftand', '0x0000901D'],
  ['BlackreachQuickExitMzinchaleft', '0x00008F75'],
  ['BlackreachSewer01', '0x0007FCDD'],
  ['BlackreachSewerEntrance', '0x0001EE6F'],
  ['BlackreachSinderionsShack', '0x000237C1'],
  ['BlackreachSpiderLair', '0x000237D0'],
  ['BlackreachSpiderLair02', '0x000237CA'],
  ['BlackreachTowers', '0x000237D8'],
  ['BlackreachWeatherTest2', '0x000237D2'],
  ['BlackreachWeatherTest3', '0x000237BE'],
  ['BlackreachZcell01', '0x0007BEF8'],
  ['BlackreachZcell02', '0x0007BEF7'],
  ['BlackreachZcell03', '0x000152BB'],
  ['BlackreachZcell04', '0x000B29D6'],
  ['BlackreachZcell05', '0x000B29D5'],
  ['BlackreachZcell06', '0x000B29D4'],
  ['BlackreachZcell07', '0x000ED8E0'],
  ['BlackreachZCell08', '0x000EEC53'],
  ['BlackreachZCell10', '0x000EEC55'],
  ['BleakcoastCave01', '0x000152BA'],
  ['BleakFallsBarrow01', '0x000371DE'],
  ['BleakFallsBarrow02', '0x000371DD'],
  ['BleakfallsBarrowPath', '0x000096F6'],
  ['BleakfallsBarrowPath02', '0x000096F7'],
  ['BleakFallsTower', '0x00009716'],
  ['BlindCliffCave01', '0x000152B7'],
  ['BlindCliffCaveCOC', '0x00021EFA'],
  ['BlindCliffCaveOrigin', '0x00020DCC'],
  ['BlindCliffCaveStart', '0x00021EF9'],
  ['BloatedMansGrottoStart', '0x00020A3C'],
  ['BloatedMansRuins', '0x00020A3E'],
  ['BloodletThrone01', '0x00016EA1'],
  ['BluePalaceWing01', '0x0009B238'],
  ['BluePalaceWingStart', '0x00034247'],
  ['BonechillPassage01', '0x0003538D'],
  ['BoulderfallCave01', '0x000681DD'],
  ['BPWArena', '0x0009B23D', 'Doesn\'t work'],
  ['BPWFear', '0x00034243', 'Doesn\'t work'],
  ['BPWHouse', '0x00034548', 'Doesn\'t work'],
  ['BPWNightmare', '0x0009B239', 'Doesn\'t work'],
  ['BPWVoid', '0x00034537', 'Doesn\'t work'],
  ['BrandyMugFarm', '0x00016205'],
  ['Brinehammer01', '0x00094322'],
  ['BrinewaterGrottoEnding', '0x00050017'],
  ['BrinewaterGrottoOrigin', '0x0005D344'],
  ['BrinewaterGrottoStart', '0x0005001C'],
  ['BrineWaterGrottoToEEW', '0x0005D33E'],
  ['BrittleShinPass01', '0x00081DEC'],
  ['BrokenFangCave01', '0x000152B1'],
  ['BrokenHelmHollow01', '0x000152B0'],
  ['BrokenLimbCamp', '0x00009623'],
  ['BrokenOarGrotto01', '0x000BA599'],
  ['BrokenTowerRedoubt01', '0x000152AF'],
  ['BrokenTowerRedoubt02', '0x0007284E'],
  ['BronzeWaterCave', '0x00054226'],
  ['BroodCavern01', '0x000152AE'],
  ['BrucasLeapRedoubt01', '0x000152AD'],
  ['Bthardamz01', '0x000361FA'],
  ['Bthardamz01a', '0x0005A857'],
  ['Bthardamz01b', '0x0005A856'],
  ['Bthardamz02', '0x000361F9'],
  ['Bthardamz02a', '0x0005912D'],
  ['Bthardamz03', '0x00030442'],
  ['ChargenExit', '0x000097EE'],
  ['ChargenStart', '0x000098A5'],
  ['ChillfurrowFarm', '0x00016204'],
  ['ChillfurrowFarmEdge', '0x00009637'],
  ['ChillwindDepths01', '0x0003E908'],
  ['CidhnaMine01', '0x00016203'],
  ['CidhnaMine02', '0x000597D4'],
  ['CidhnaMine03', '0x0005A01A'],
  ['ClearspringTarn01', '0x000152A2'],
  ['CliffsideRetreat', '0x00009411'],
  ['ColdRockPass01', '0x00054D0E'],
  ['CrackedTuskKeep01', '0x0001526A'],
  ['CrackedTuskKeep02', '0x00065AB6'],
  ['CragslaneCavern01', '0x000152A5'],
  ['CragwallowSlope01', '0x000152A8'],
  ['CronvangrHall01', '0x000152A7'],
  ['CronvangrHall02', '0x0002D5D1'],
  ['CrystaldriftCave01', '0x000152A0'],
  ['CTest', '0x000B1783'],
  ['CWCampsiteWhiterun', '0x00009105'],
  ['CWGuardTemplates', '0x0001FA4C'],
  ['CWMessageMarkers', '0x000221B5'],
  ['CWMission07ImperialCamp01', '0x000094B2'],
  ['CWMission07ImperialCamp02', '0x000094B3'],
  ['CWMission07ImperialCamp03', '0x00009492'],
  ['CWMission07ImperialCamp04', '0x00009493'],
  ['CWMission07SonsCamp', '0x0000BB25'],
  ['CWMission07SonsCamp02', '0x0000BB46'],
  ['CWMission07SonsCamp03', '0x0000BB45'],
  ['CWPatrolsPaleImperial', '0x0000928E'],
  ['CWPatrolsPaleSons', '0x000090B5'],
  ['CWPatrolsWinterholdImperial', '0x00008EEF'],
  ['CWQuartermasterContainers', '0x000FE47B'],
  ['DA02BoethiahShrine', '0x0000B4F6'],
  ['DA02BoethiahShrine2', '0x0000B4F5'],
  ['DA13PeryiteShrine', '0x0000707C'],
  ['DA14Interior', '0x0003D62B'],
  ['DaintySload01', '0x0007B7AB'],
  ['DarkBrotherhoodSanctuary', '0x000AD5A1'],
  ['DarklightTower01', '0x0001529F'],
  ['DarklightTower02', '0x0003CBCB'],
  ['Darkshade01', '0x00015296'],
  ['DarkwaterCavernExit', '0x0002C98E'],
  ['DarkwaterCavernOrigin', '0x0002C997'],
  ['DarkwaterCavernStart', '0x0002C996'],
  ['DarkwaterCavernW01', '0x0002C992'],
  ['DarkwaterCrossingGoldenrockMine', '0x00013A8A'],
  ['DarkwaterCrossingVernersHouse', '0x00013A8C'],
  ['DawnstarBarracks', '0x00013A89'],
  ['DawnstarBarracksJail', '0x000EB440'],
  ['DawnstarBeitildsHouse', '0x00013A88'],
  ['DawnstarBrinasHouse', '0x00013A87'],
  ['DawnstarFrukisHouse', '0x00013A81'],
  ['DawnstarIrgnirsHouse', '0x00013A85'],
  ['DawnstarIronBreakerMine', '0x0002C778'],
  ['DawnstarLeigelfsHouse', '0x00013A84'],
  ['DawnstarMortarandPestle', '0x00013A86'],
  ['DawnstarQuicksilverMine', '0x0002C779'],
  ['DawnstarRustleifsHouse', '0x00013A83'],
  ['DawnstarSanctuary', '0x000193EE'],
  ['DawnstarSilussHouse', '0x000240B7'],
  ['DawnstarTheWhiteHall', '0x00013A80'],
  ['DawnstarWindpeakInn', '0x00013A7F'],
  ['DeadCroneRock01', '0x00015295'],
  ['DeadMensRespite01', '0x0001529D'],
  ['DeekusCamp', '0x00008E14'],
  ['DeepwoodRedoubt01', '0x0001529C'],
  ['DeepwoodRedoubtOriginNew', '0x000982A0'],
  ['DeepwoodRedoubtStart', '0x00029AF2'],
  ['DoomstoneFallForest01', '0x0000BD34'],
  ['DoomstoneNorthernCoast01', '0x0000B223'],
  ['DoomstoneNorthernCoast02', '0x0000B222'],
  ['DoomstoneNorthernCoast03', '0x0000B202'],
  ['DoomstoneNorthernCoast04', '0x0000B201'],
  ['DoomstoneNorthernPineForest01', '0x0000921F'],
  ['DoomstonePineForest01', '0x00009B78'],
  ['DoomstoneReach01', '0x00007118'],
  ['DoomstoneSnowy01', '0x00008EAB'],
  ['DoomstoneSnowy02', '0x0000902F'],
  ['DoomstoneTundra01', '0x000095F4'],
  ['DoomstoneTundraMarsh01', '0x0000933E'],
  ['DoomstoneVolcanicTundra', '0x0000969B'],
  ['DragonBridgeFarm', '0x00013A7E'],
  ['DragonBridgeFourShieldsTavern', '0x00013A7C'],
  ['DragonBridgeHorgeirsHouse', '0x00013A7A'],
  ['DragonBridgeLumberCamp', '0x00013A7D'],
  ['DragonBridgePenitusOculatusOutpost', '0x00013A7B'],
  ['DragonMoundFallForest01', '0x0000BD75'],
  ['DragonMoundFallForest02', '0x0000BC53'],
  ['DragonMoundFallForest03', '0x00009874'],
  ['DragonMoundPineForest01', '0x000098E5'],
  ['DragonMoundPineForest02', '0x00009C01'],
  ['DragonMoundPineForest03', '0x00009ADE'],
  ['DragonMoundReach01', '0x000070DC'],
  ['DragonMoundReach02', '0x000099E2'],
  ['DragonMoundReach03', '0x00006FA1'],
  ['DragonMoundSnowy01', '0x00008EF9'],
  ['DragonMoundSnowy02', '0x00009094'],
  ['DragonMoundTundra01', '0x00009AB6'],
  ['DragonMoundTundra02', '0x0000915B'],
  ['DragonMoundTundra03', '0x000099B9'],
  ['DragonMoundTundra04', '0x0000958B'],
  ['DragonMoundTundraMarsh01', '0x00009408'],
  ['DragonMoundTundraMarsh02', '0x00009344'],
  ['DragonMoundTundraMarsh03', '0x00009420'],
  ['DragonMoundVolcanicTundra01', '0x0000BA82'],
  ['DragonMoundVolcanicTundra02', '0x00009620'],
  ['DragonMoundVolcanicTundra03', '0x000095A3'],
  ['DrelasCottage01', '0x000DEBCD'],
  ['DrelassCottage', '0x000094E5'],
  ['DriftshadeSanctuary01', '0x00015288'],
  ['DriftshadeSanctuary02', '0x0003DD34'],
  ['DruadachRedoubt01', '0x0004401B'],
  ['DushnikhYalCellar', '0x00065AB5'],
  ['DushnikhYalLonghouse', '0x000198E2'],
  ['DushnikhYalMine', '0x0001528A'],
  ['DuskglowCrevice01', '0x00015290'],
  ['DustmansCairn01', '0x0001528C'],
  ['DustmansCairn02', '0x0002A03A'],
  ['E3demoBleakFallsBarrow', '0x00075669'],
  ['E3demoDragon02Lair', '0x00009678'],
  ['EEWtoBrinewaterGrotto', '0x0004F83A'],
  ['EldergleamSanctuaryStart', '0x0003A9EC'],
  ['EldergleamSanctuaryStart02', '0x0003A9E0'],
  ['EldergleamSanctuaryTop', '0x0003A9E3'],
  ['Elsweyr', '0x000B9BC6', 'It\'s just a box'],
  ['EmbershardMine01', '0x000B6BE6'],
  ['FaldarsTooth01', '0x00015286'],
  ['FalkreathBarracks', '0x000EF325'],
  ['FalkreathBarracksJail', '0x000EF324'],
  ['FalkreathCorpselightFarm', '0x00013A72'],
  ['FalkreathDeadMansDrink', '0x0003A184'],
  ['FalkreathDengeirsHall', '0x00013A78'],
  ['FalkreathGraveConcoctions', '0x0003A183'],
  ['FalkreathGrayPineGoods', '0x00013A76'],
  ['FalkreathHouseofArkay', '0x00013A71'],
  ['FalkreathJarlsLonghouse', '0x00013A79'],
  ['FalkreathLodsHouse', '0x00013A73'],
  ['FallowstoneCave', '0x00024411'],
  ['FallowstoneCaveEnd', '0x000204EC'],
  ['FallowstoneCaveExit', '0x000243F3'],
  ['FallowstoneCaveOrigin', '0x000243F8'],
  ['FallowstoneCaveStartNew', '0x0002440C'],
  ['FellglowKeep01', '0x00015283'],
  ['FellglowKeep02', '0x0003FF10'],
  ['FellglowKeep03', '0x000C9DAB'],
  ['Folgunthur01', '0x00015280'],
];
// Creatures the team has tested, with what they found. Anything marked with a
// note is somebody's own finding, not a guess.
const CREATURES = [
  { group: 'Bruma and Cyrodiil', rows: [
    ['Scamp', '0x05601FAE', 'Insanely weak, deals almost no damage. Drops scamp skin.'],
    ['Prime Scamp', '0x0560292D', 'Deals good damage but very weak. Fireball, fire cloak, firebolt.'],
    ['Ayleid Spellblade', '0x060B5579', 'Working bound sword Ayleid. CYRdunAyleidSkeleton06BossMelee.'],
    ['Ayleid Lich', '0x056026FD', 'Big damage and huge health. Boss enemy, very strong.'],
    ['Ayleid bound sword and chain lightning', '0x060B5578', 'CYRdunAyleidSkeleton06BossLich.'],
    ['Werewolf', '0x060718EF', 'Working werewolf boss. Hits like a truck, extreme health. Drops ebony armour, weapons and ores. Armour can break on a jump attack.'],
    ['Zombie, level 2', '0x0560242B', 'Drops bonemeal.'],
    ['Zombie, level 40', '0x060D546D', 'Drops bonemeal, stronger than the level 2.'],
    ['Boar', '0x0606DA7A', 'Medium damage, extreme health, no drops.'],
    ['Mountain Lion', '0x0605F055', 'Hurts. A sabrecat but smaller.'],
    ['Timberwolf', '0x056018A6', 'Low damage, a reskinned standard wolf.'],
    ['Packwolf', '0x0607264D', ''],
    ['Hunting Dog', '0x0606F93A', 'A wolf, near enough.'],
    ['Rat', '0x0560242A', ''],
    ['Moss Troll', '0x0604932A', ''],
    ['Moss Mudcrab, large', '0x060038FE', ''],
    ['Moss Mudcrab, small', '0x060038FC', ''],
    ['Boss Spriggan', '0x000F3905', ''],
    ['Lesser Spriggan', '0x00023AB9', ''],
    ['Gray Fox', '0x06071A81', ''],
    ['Bruma Deer', '0x0604932F', ''],
    ['Black Bear', '0x0604932C', '']
  ]},
  { group: 'Goblins', note: 'Do not mix goblin tribes. They will attack each other.', rows: [
    ['Goblin (missile)', '0x0560293A', 'Also 0x0560260A.'],
    ['Goblin Archer', '0x0560262B', ''],
    ['Goblin Bruiser (missile)', '0x0560262A', ''],
    ['Goblin Butcher (missile)', '0x05602629', ''],
    ['Goblin Marksman', '0x05602627', ''],
    ['Goblin Deadeye', '0x05602660', '']
  ]},
  { group: 'Bald Tail goblins', note: 'One tribe, so these may be used together.', rows: [
    ['Goblin Boss, melee', '0x060E9E1E', 'CYRLvlGoblinBossMeleeBaldTail'],
    ['Goblin, melee', '0x060E9E1F', 'CYRLvlGoblinMeleeBaldTail'],
    ['Goblin, missile', '0x060E9E20', 'CYRLvlGoblinMissileBaldTail'],
    ['Skirmisher, berserker', '0x060E9E21', 'CYREncGoblinBaldTail02Berserker'],
    ['Shaman', '0x060E9E22', 'CYREncGoblinBaldTail02BossMagic'],
    ['Warlord', '0x060E9E23', 'CYREncGoblinBaldTail02BossMelee'],
    ['Skirmisher, melee', '0x060E9E24', 'CYREncGoblinBaldTail02Melee'],
    ['Skirmisher, missile', '0x060E9E25', 'CYREncGoblinBaldTail02Missile'],
    ['Bruiser, berserker', '0x060E9E26', 'CYREncGoblinBaldTail03Berserker'],
    ['Shaman', '0x060E9E27', 'CYREncGoblinBaldTail03BossMagic'],
    ['Warlord', '0x060E9E28', 'CYREncGoblinBaldTail03BossMelee'],
    ['Bruiser, melee', '0x060E9E29', 'CYREncGoblinBaldTail03Melee'],
    ['Bruiser, missile', '0x060E9E2A', 'CYREncGoblinBaldTail03Missile'],
    ['Butcher, berserker', '0x060E9E2B', 'CYREncGoblinBaldTail04Berserker'],
    ['Shaman', '0x060E9E2C', 'CYREncGoblinBaldTail04BossMagic'],
    ['Warchief', '0x060E9E2D', 'CYREncGoblinBaldTail04BossMelee'],
    ['Butcher, melee', '0x060E9E2E', 'CYREncGoblinBaldTail04Melee'],
    ['Butcher, missile', '0x060E9E2F', 'CYREncGoblinBaldTail04Missile'],
    ['Savage, berserker', '0x060E9E30', 'CYREncGoblinBaldTail05Berserker'],
    ['Shaman', '0x060E9E31', 'CYREncGoblinBaldTail05BossMagic'],
    ['Warchief', '0x060E9E32', 'CYREncGoblinBaldTail05BossMelee'],
    ['Savage, melee', '0x060E9E33', 'CYREncGoblinBaldTail05Melee'],
    ['Savage, missile', '0x060E9E34', 'CYREncGoblinBaldTail05Missile'],
    ['Warlord, berserker', '0x060E9E35', 'CYREncGoblinBaldTail06Berserker'],
    ['Shaman', '0x060E9E36', 'CYREncGoblinBaldTail06BossMagic'],
    ['Warchief', '0x060E9E37', 'CYREncGoblinBaldTail06BossMelee'],
    ['Warlord, melee', '0x060E9E38', 'CYREncGoblinBaldTail06Melee'],
    ['Warlord, missile', '0x060E9E39', 'CYREncGoblinBaldTail06Missile']
  ]},
  { group: 'Gold Finger goblins', note: 'A separate tribe again — keep them apart from the Bald Tails.', rows: [
    ['Gold Finger Goblin, berserker', '0x060E9E48', 'CYREncGoblinGoldFinger01aBerserker'],
    ['Gold Finger Goblin, melee', '0x060E9E49', 'CYREncGoblinGoldFinger01aMelee'],
    ['Gold Finger Goblin, missile', '0x060E9E4A', 'CYREncGoblinGoldFinger01aMissile'],
    ['Gold Finger Goblin, berserker', '0x060E9E4B', 'CYREncGoblinGoldFinger01Berserker'],
    ['Gold Finger Goblin Shaman', '0x060E9E4C', 'CYREncGoblinGoldFinger01BossMagic']
  ]},
  { group: 'Skyrim wildlife', rows: [
    ['Deer', '0x000CF89D', ''],
    ['Elk', '0x00023A91', ''],
    ['Fox', '0x000829B3', ''],
    ['Snow Fox', '0x000829B6', ''],
    ['Rabbit', '0x0006DC9D', ''],
    ['Bear', '0x00023A8A', ''],
    ['Snow Bear', '0x00023A8C', ''],
    ['Ice Wolf', '0x00023ABF', 'Bruma variant is 0x06003C86.'],
    ['Snow Cat', '0x00023AB6', ''],
    ['Cow', '0x00023A90', ''],
    ['Chicken', '0x000A91A0', ''],
    ['Frost Atronach', '0x000204C1', ''],
    ['Frost Troll', '0x00023ABB', ''],
    ['Ice Wraith', '0x00023AB3', '']
  ]}
];

const DUNGEONS = [
  { group: 'Caves and dungeons', rows: [
    ['Capstone Cave', '0x0605B9D0', 'Done. A very hard cave.'],
    ['Boreal Stone Cave', '0x0607CB7E', ''],
    ['Underpall Cave', '0x060B45F8', 'The second half was left without enemies on purpose — a good RP spot.'],
    ['Hjalti’s Refuge', '0x0608720D', ''],
    ['Silver Tooth Cave', '0x06087D16', ''],
    ['Red Ruby Cave', '0x06084297', ''],
    ['Unmarked Cave', '0x060CBC2D', ''],
    ['Frostfire Glade', '0x0606BF7B', 'Will not go past stage 8. The rest of the cave cannot be made part of the dungeon.'],
    ['Freezewind Hollow', '0x06079F0D', 'Done. A small, easy spider cave.'],
    ['Northfringe Cave', '0x06089382', '']
  ]},
  { group: 'Jasper', rows: [
    ['Serpent’s Trail', '0x060796A9', ''],
    ['Toadstool Hollow', '0x060796A9', ''],
    ['Rielle', '0x060CBAE8', ''],
    ['The Beast’s Maw', '0x0608BDB0', '']
  ]},
  { group: 'Chests', rows: [
    ['Anga chest', '0x060DEFC8', ''],
    ['Maw of Sedor chest', '0x06088EA0', ''],
    ['Sedor chest', '0x0608B569', '']
  ]}
];

const ITEM_SEED = [
  ['Amulet of Mara', '0x060ED24B', 'Divine amulet'],
  ['Amulet of Stendarr', '0x060EEC27', 'Divine amulet'],
  ['Amulet of Zenithar', '0x060EEC29', 'Divine amulet'],
  ['Amulet of Julianos', '0x05602993', 'Divine amulet'],
  ['Amulet of Dibella', '0x05602995', 'Divine amulet'],
  ['Thornblade', '0x060EE5C5', 'Unique weapon'],
  ['Goldbrand', '0x060DF0F0', 'Unique weapon'],
  ['Hvitbrand', '0x060D383B', 'Unique weapon'],
  ['Steel Nodachi', '0x05601AB6', 'Weapon'],
  ['Iron Katana', '0x05601AC5', 'Weapon'],
  ['Nodachi, Daedric', '0x06078F5D', 'Weapon'],
  ['Clasomo’s Stormblade', '0x0608BCCC', 'Unique model'],
  ['Ayleid Mage Robes', '0x060E36FF', 'Ayleid apparel'],
  ['Ayleid Mage Hood', '0x060E3701', 'Ayleid apparel'],
  ['Ayleid Armguards', '0x060E3703', 'Ayleid apparel'],
  ['Ayleid Mage Boots', '0x060E3705', 'Ayleid apparel'],
  ['Ayleid Amulet', '0x060D4A8E', 'Ayleid apparel'],
  ['Ayleid Ring', '0x060D4A8C', 'Ayleid apparel'],
  ['Ayleid Staff of Lightning Bolt', '0x056028DB', 'Ayleid'],
  ['Ayleid Lich Helm', '0x056026FF', 'Ayleid'],
  ['Ayleid Dagger', '0x06300065', 'Ayleid'],
  ['Ayleid Sword', '0x06300068', 'Ayleid'],
  ['Ayleid Bow', '0x06300064', 'Ayleid'],
  ['Ayleid Arrows', '0x0605F035', 'Ayleid'],
  ['Aranedean Sword', '0x060EF659', 'Different from the Alkid sword'],
  ['Third Era Iron Sword', '0x05601AA1', 'Weapon'],
  ['Steel Tanto', '0x05601A99', 'Weapon'],
  ['New Pickaxe', '0x0560258A', 'Tool'],
  ['Hatchet', '0x0560259C', 'Tool'],
  ['Hand Axe', '0x056025BF', 'Weapon'],
  ['Wooden Club', '0x05601AC8', 'Weapon'],
  ['Lute', '0x0606E7B3', 'Instrument'],
  ['Minotaur war hammer axe', '0x056026E6', 'Weapon'],
  ['Eastern Dwemer Axe', '0x05601ACF', 'Weapon'],
  ['Glass Scimitar', '0x05601AB4', 'Weapon'],
  ['Steel Scimitar', '0x05601AB0', 'Weapon'],
  ['Silver Battle Staff', '0x05601AAB', 'Weapon'],
  ['Silver Battleaxe', '0x05601ACB', 'Silver Hand'],
  ['Perfect Silver Battleaxe', '0x05601ACC', 'Silver Hand'],
  ['Silver War Axe', '0x05601ACD', 'Silver Hand'],
  ['Perfect Silver Axe', '0x05601ACE', 'Silver Hand'],
  ['Perfect Silver Longsword', '0x05601ABD', 'Silver Hand'],
  ['Silver Mace', '0x060AEB00', 'Silver Hand'],
  ['Goblin Shield variant', '0x060E9DB6', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DBE', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DBF', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DC0', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DC1', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DC2', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DC3', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DC4', 'Goblin shields, different variants'],
  ['Goblin Shield variant', '0x060E9DCD', 'Goblin shields, different variants'],
  ['House Keys', '0x1601024B', 'Already in additem form'],
  ['Ancient Nord Arrow', '0x00034182', 'Arrow'],
  ['Daedric Arrow', '0x000139C0', 'Arrow'],
  ['Dwarven Arrow', '0x000139BC', 'Arrow'],
  ['Ebony Arrow', '0x000139BF', 'Arrow'],
  ['Elven Arrow', '0x000139BD', 'Arrow'],
  ['Falmer Arrow', '0x00038341', 'Arrow'],
  ['Forsworn Arrow', '0x000CEE9E', 'Arrow'],
  ['Glass Arrow', '0x000139BE', 'Arrow'],
  ['Iron Arrow', '0x0001397D', 'Arrow'],
  ['Nordic Arrow', '0x0402623B', 'Arrow'],
  ['Orcish Arrow', '0x000139BB', 'Arrow'],
  ['Practice Arrow', '0x000CAB52', 'Arrow'],
  ['Rusty Arrow', '0x000E738A', 'Arrow'],
  ['Steel Arrow', '0x0001397F', 'Arrow'],
  ['Steel Bolt', '0x02000BB3', 'Bolt']
];

const RECORDING = [
  ['tfc', 'Free camera. Add a 1 to freeze everything where it stands: <code>tfc 1</code>.'],
  ['sucsm 4', 'Free camera speed. Four is the one the team uses for recording — slow and steady.'],
  ['tm', 'Hide the interface. Type it again to bring it back; the console still works while it is off.'],
  ['tgp', 'Hide the grass, when it gets in the way of the shot.'],
  ['fov 70', 'Set the field of view. Anything from 60 to 90 reads well on camera.'],
  ['set timescale to 1', 'Stop the sky racing. Ten is the default, one is real time, zero holds the hour.'],
  ['fw &lt;weatherid&gt;', 'Force the weather. On this server use <code>/forceweather</code> instead — it carries to everyone.'],
  ['tai', 'Freeze every NPC where it stands.'],
  ['tcai', 'Stop NPCs fighting without freezing them.']
];

const CONSOLE = [
  { group: 'Getting about', rows: [
    ['coc &lt;EditorID&gt;', 'Travel to a cell by its editor id. Every cell the team has is under Locations.'],
    ['cow &lt;worldspace&gt; &lt;x&gt; &lt;y&gt;', 'Travel to a place in the open world by cell grid.'],
    ['tcl', 'Walk through walls. Clears a stuck character.'],
    ['player.moveto &lt;refid&gt;', 'Go to a reference.'],
    ['moveto player', 'Bring the selected reference to you.']
  ]},
  { group: 'Looking at things', rows: [
    ['help "&lt;name&gt;" 0', 'Search every form id by name. The way to find an id you do not have.'],
    ['prid &lt;refid&gt;', 'Select a reference by id rather than clicking it.'],
    ['&lt;click&gt;', 'Clicking a thing with the console open selects it and prints its ref id.'],
    ['sexchange', 'Switch the selected character’s sex.'],
    ['showracemenu', 'The race menu. On this server do not use it on a deformed character — have them relog.']
  ]},
  { group: 'Things and money', rows: [
    ['player.additem &lt;id&gt; &lt;count&gt;', 'The vanilla version. On this server use <code>/additem</code> so it is recorded.'],
    ['player.removeitem &lt;id&gt; &lt;count&gt;', 'Take something away.'],
    ['player.additem 0000000f &lt;count&gt;', 'Gold.'],
    ['player.equipitem &lt;id&gt;', 'Put something on.'],
    ['player.drop &lt;id&gt; &lt;count&gt;', 'Drop it on the floor.']
  ]},
  { group: 'People and creatures', rows: [
    ['player.placeatme &lt;baseid&gt; &lt;count&gt;', 'Put a creature or NPC in front of you. The bestiary has the ids.'],
    ['disable', 'Make the selected thing vanish.'],
    ['enable', 'Bring it back.'],
    ['markfordelete', 'Mark it gone for good on the next load.'],
    ['resurrect', 'Raise the selected body. <code>resurrect 1</code> keeps its inventory.'],
    ['kill', 'Kill the selected thing.'],
    ['setessential &lt;baseid&gt; 1', 'Make something unkillable. Zero undoes it.'],
    ['setrelationshiprank player &lt;-4..4&gt;', 'Make something friendly or hostile to the player.']
  ]},
  { group: 'The character', rows: [
    ['player.setav &lt;skill&gt; &lt;n&gt;', 'Set a skill or attribute.'],
    ['player.modav &lt;skill&gt; &lt;n&gt;', 'Change one by an amount.'],
    ['player.setlevel &lt;n&gt;', 'Set the level.'],
    ['advskill &lt;skill&gt; &lt;n&gt;', 'Grant skill experience.'],
    ['player.addspell &lt;id&gt;', 'Teach a spell. On this server <code>/learnspell</code> is the recorded way.'],
    ['player.removespell &lt;id&gt;', 'Take a spell back.'],
    ['player.addperk &lt;id&gt;', 'Grant a perk.'],
    ['player.addshout &lt;id&gt;', 'Grant a shout.'],
    ['psb', 'Every spell in the game. Rarely what you want.'],
    ['tgm', 'God mode.'],
    ['tim', 'Immortal but still takes damage.'],
    ['tdetect', 'Nobody can see you.']
  ]},
  { group: 'The world', rows: [
    ['set gamehour to &lt;0-23&gt;', 'Set the hour.'],
    ['set timescale to &lt;n&gt;', 'How fast time runs. Ten is default.'],
    ['fw &lt;weatherid&gt;', 'Force weather for you alone.'],
    ['sw &lt;weatherid&gt;', 'Set the weather so it changes naturally from there.'],
    ['unlock', 'Unlock the selected door or container.'],
    ['lock &lt;1-100&gt;', 'Lock it. On this server use <code>/lockdoor</code> and <code>/lockchest</code>.']
  ]}
];

const SERVER_COMMANDS = [
  { group: 'General and player', rows: [
    ['/help', 'Show the list of available commands'],
    ['/pos', 'Show your current position'],
    ['/players', 'List all online players'],
    ['/roll', 'Roll a die, between 1 and 9999'],
    ['/notes', 'Open your personal notebook'],
    ['/gm', 'Send a help request to online staff'],
    ['/dm', 'Send a private message to a player'],
    ['/lastconnected', 'Check when a player last connected'],
    ['/stuck', 'Free your character when physically stuck'],
    ['/return', 'Return to your position before the last teleport']
  ]},
  { group: 'Teleportation and position', rows: [
    ['/teleport', 'Teleport to a location or FormID'],
    ['/tpto', 'Teleport to a player position'],
    ['/bring', 'Bring a player to your position'],
    ['/bringall', 'Bring all players to your position'],
    ['/addpos', 'Add a value to X, Y or Z'],
    ['/setpos', 'Set your position to specific coordinates'],
    ['/tpchest', 'Teleport to a chest or ref by FormID or description']
  ]},
  { group: 'Combat and death', rows: [
    ['/kill', 'Kill yourself'],
    ['/slay', 'Slay a player'],
    ['/killall', 'Kill all actors with a specific baseId'],
    ['/revive', 'Revive a dead player'],
    ['/destroy', 'Destroy an NPC or actor by ref id'],
    ['/ajail', 'Send a player to the Soul Cairn']
  ]},
  { group: 'Player management', rows: [
    ['/kick', 'Kick someone from the game'],
    ['/ban', 'Ban a player by IP address — but use the admin website instead'],
    ['/mute', 'Mute a player’s voice chat'],
    ['/unmute', 'Unmute a player’s voice chat'],
    ['/handcuff', 'Restrict a player’s controls'],
    ['/unhandcuff', 'Remove handcuffs'],
    ['/rename', 'Rename a player'],
    ['/renamep', 'Rename a player by profileId'],
    ['/resetknown', 'Reset a player’s known characters list'],
    ['/eval', 'Send an eval to a player'],
    ['/consoleallow', 'Toggle console commands for a player'],
    ['/pconsoleallow', 'Toggle partial console commands for a player'],
    ['/deletecharacter', 'Delete a player’s current character']
  ]},
  { group: 'Character and appearance', rows: [
    ['/race', 'Change a player’s race'],
    ['/racemenu', 'Open the race menu for a player — never for a deformed character'],
    ['/pracemenu', 'Open the race menu for a player'],
    ['/cracemenu', 'Close a stuck race menu'],
    ['/setappearance', 'Set appearance from a JSON file'],
    ['/appdebug', 'Report a player’s clientside head parts'],
    ['/setvampire', 'Turn a player into a vampire'],
    ['/vamp', 'Toggle vampire headparts'],
    ['/setwerewolf', 'Toggle werewolf form'],
    ['/forgemaster', 'Toggle Forgemaster morph'],
    ['/disguise', 'Disguise yourself with the required item'],
    ['/playidle', 'Play an idle animation']
  ]},
  { group: 'Skills, spells and perks', rows: [
    ['/additem', 'Add an item to a player'],
    ['/learnspell', 'Teach a spell to a player'],
    ['/removespell', 'Remove a spell by FormID'],
    ['/removeallspells', 'Remove all spells'],
    ['/addperk', 'Add a perk by FormID'],
    ['/grantskill', 'Grant a skill tier'],
    ['/resetmastery', 'Reset skill mastery'],
    ['/wlock', 'Grant the expert lockpicking perk'],
    ['/wunlock', 'Remove the expert lockpicking perk']
  ]},
  { group: 'Stats, horses and hunger', rows: [
    ['/setrespawnav', 'Set respawn health, magicka or stamina percentage'],
    ['/hunger', 'Show hunger level and stats'],
    ['/sethunger', 'Set a player’s hunger level'],
    ['/h', 'Open the horse management menu (debug)'],
    ['/horse', 'Assign a horse to a player'],
    ['/rhorse', 'Remove a horse from a player']
  ]},
  { group: 'Housing', rows: [
    ['/houses', 'List available houses'],
    ['/managehouse', 'Open the housing management menu'],
    ['/granthouse', 'Grant the door you are looking at to a player, in first person'],
    ['/ungranthouse', 'Ungrant the door you are looking at, in first person'],
    ['/addguest', 'Add a guest to your house'],
    ['/removeguest', 'Remove a guest'],
    ['/listguests', 'List house guests'],
    ['/lockhouse', 'Lock your house'],
    ['/rentmenu', 'Open the per-house rent menu'],
    ['/createhouse', 'Create a house definition from the door you are looking at'],
    ['/adddoor', 'Add the door you are looking at to a house'],
    ['/deldoor', 'Remove the door you are looking at from a house'],
    ['/linkhouse', 'Link a house as a child of another — easiest from the /amenu housing menu'],
    ['/unlinkhouse', 'Unlink a house bundle — easiest from the /amenu housing menu']
  ]},
  { group: 'Objects and items', rows: [
    ['/remove', 'Remove an object by FormID'],
    ['/enable', 'Enable an ObjectReference'],
    ['/disable', 'Disable an ObjectReference'],
    ['/findid', 'Find item FormIDs'],
    ['/spawn', 'Spawn an NPC or object'],
    ['/place', 'Place a persistent synced static'],
    ['/delete', 'Delete a server-placed object'],
    ['/placeboard', 'Place a persistent notice board'],
    ['/placemode', 'Enter furniture placement mode'],
    ['/cellnpcs', 'List spawnable NPCs and leveled lists']
  ]},
  { group: 'Doors and chests', rows: [
    ['/lockdoor', 'Lock or unlock the door you are looking at, in first person'],
    ['/grantchest', 'Grant the container you are looking at, in first person'],
    ['/ungrantchest', 'Ungrant the container you are looking at, in first person'],
    ['/lockchest', 'Add a lock to the chest you are looking at, in first person']
  ]},
  { group: 'Dungeons', rows: [
    ['/createdg', 'Create a dungeon'],
    ['/addnpcdg', 'Add an NPC to a dungeon'],
    ['/setdistdg', 'Set exterior dungeon detection distance'],
    ['/setchestdg', 'Set the dungeon loot chest'],
    ['/resetcddg', 'Reset dungeon cooldown'],
    ['/setcddg', 'Set dungeon cooldown'],
    ['/setchasedg', 'Set the exterior dungeon chase timer'],
    ['/removedg', 'Remove a dungeon'],
    ['/addstagedg', 'Add a dungeon stage'],
    ['/setcheckpointdg', 'Set a stage checkpoint'],
    ['/addchestdg', 'Add a chest to a dungeon stage'],
    ['/setblockerdg', 'Manage dungeon entrance blockers'],
    ['/setopencountdg', 'Set the number of simultaneously open dungeons'],
    ['/forceweeklyresetdg', 'Force the weekly dungeon rotation reset'],
    ['/setblockeddg', 'Block or unblock a dungeon'],
    ['/dgmenu', 'Open the dungeon admin panel']
  ]},
  { group: 'Cinematic, testing and world', rows: [
    ['/cinematic', 'Start the cinematic camera effect'],
    ['/track', 'Toggle cinematic track mode'],
    ['/invis', 'Toggle actor visibility'],
    ['/phantom', 'Toggle the GhostVeil effect'],
    ['/mocktrade', 'Open a trade menu with yourself'],
    ['/startquest', 'Start KzlQuestMotd and set stage 10'],
    ['/amenu', 'Open the admin menu'],
    ['/forceweather', 'Force weather on all players'],
    ['/resetjobcd', 'Reset the shared hay and firewood farming cooldown'],
    ['/accept', 'Accept a pending trade request']
  ]}
];

const HOWTO = [
  {
    head: 'Renaming a player',
    body: 'Quotation marks mark the old name; the second entry is the new one.',
    pre: '/rename "John Oblivion" "John Skyrim"',
    after: 'If two players share a name, or a name is stuck as “Stranger”, rename by profile id instead. A profile id is not a form id — find it through /amenu in game, or in the bottom right of /findbyformid in Discord.',
    pre2: '/renamep 1108 "Anders Alderson"'
  },
  {
    head: 'Finding a player through the logs',
    body: 'When /findbyformid returns “No Discord”, the person has either left the community or deleted their character. Convert their form id to decimal — every player id follows the 0xFF0AAAAA convention — and search the decimal in the server logs.',
    pre: '0xFF01BC85  →  4278303877',
    after: 'Search that decimal in the logs, then search the player’s name. If the actor id matches the original form id, that is your player, and you can check their Discord for earlier punishment.'
  },
  {
    head: 'Creating a house',
    body: 'The id is the code you invent to link the door and is never seen on it. The name is the yellow text that appears on the door. The city is only for the record.',
    pre: '/createhouse Dragonsreach_Front_Door Dragonsreach Whiterun',
    after: 'Then look at the door and link it. The door will show the name you set. After that, master-lock it, hold X on the door, choose Grant House, press F6 and type the player’s name. Chests are the same — grant, then /lockchest 100.',
    pre2: '/adddoor Dragonsreach_Front_Door\n/lockdoor 100'
  }
];

const WARNINGS = {
  lede: 'Warnings are issued on Discord with /warn against the account of the person being warned. Get their Discord id first — with developer mode on, right click the user and Copy User ID — so the warning lands on the right person.',
  purposes: [
    'To tell a player they have gone outside the rules.',
    'To give a lesser punishment than a ban.',
    'To let staff track rule breaks and see a pattern of behaviour.'
  ],
  format: '| Rule break | What they were doing | How it breaks the rules | What they can do better |',
  note: 'Say plainly what the rule break was and what they did to earn the warning. Many players are warned without ever understanding what they did wrong. Be polite and understanding — a warning written this way is clear to the player and gives context to the next GM.'
};

const BANS = {
  lede: 'A first offence in an isolated case should be a warning. Use your judgement.',
  rows: [
    ['5 days', 'Mild offences — lashing out, arguing in bad faith, breaking immersion, minor glitch use.'],
    ['15 days', 'FearRP, New Life Rule violations, breaking Banditry rules.'],
    ['30 days', 'RDM, metagaming, prominent OOC bleed.'],
    ['Permanent', 'Exploiting server or Skyrim mechanics, intentional trolling or breaking immersion, actively harassing community members.']
  ],
  important: 'When issuing a temporary ban, use <code>/note</code> and duplicate the ban message you gave in <code>/ban</code>. Temporary bans are not permanently recorded; a note is a permanent record that players do not see, unlike ban messages.'
};

module.exports = { CELLS, CREATURES, DUNGEONS, ITEM_SEED, RECORDING, CONSOLE, SERVER_COMMANDS, HOWTO, WARNINGS, BANS };
